$$
\textbf{Question 1:}\\
\textbf{Markov process}
$$
$
Given\;that\\
TT + (TS\;or\;TT)---->TT\;with\;probability=1/2,(TS\;or\;ST)\;with\;probability=1/2.\\
(a)\implies Possible\;states\;are\;TT,TS\rightarrow TT,TS\;or\;ST.\\
SS,TS\rightarrow SS,ST\;or\;TS.\\
TS,TS\rightarrow\;TT,TS\;or\;ST,SS.\\
\implies Transition\;matrix\;is\left(\begin{array}{cc} 
P_{TT-TT} & P_{TT-TS} & P_{TT-SS}\\
P_{TS-TT} & P_{TS-TS} & P_{TS-SS}\\
P_{SS-TT} & P_{SS-TS} & P_{SS-SS}
\end{array}\right)
=\left(\begin{array}{cc} 
1/2 & 1/2 & 0\\
1/4 & 1/2 & 1/4\\
0 & 1/2 & 1/2
\end{array}\right)
$

$
(b)We\;start\;with\;a\;medium\;height\;individual\;(as\;the\;first\;partner).
\implies Second\;generation\;transition\;matrix=(Transition\;matrix)^{2}=
\left(\begin{array}{cc} 
1/2 & 1/2 & 0\\
1/4 & 1/2 & 1/4\\
0 & 1/2 & 1/2
\end{array}\right)
*\left(\begin{array}{cc} 
1/2 & 1/2 & 0\\
1/4 & 1/2 & 1/4\\
0 & 1/2 & 1/2
\end{array}\right)
=(1/4)^{2}\left(\begin{array}{cc} 
6 & 8 & 2\\
4 & 8 & 4\\
2 & 8 & 6
\end{array}\right)\\
\implies Third\;generation\;transition\;matrix=(Transition\;matrix)^{3}=
(1/4)^{2}\left(\begin{array}{cc} 
6 & 8 & 2\\
4 & 8 & 4\\
2 & 8 & 6
\end{array}\right)
*\left(\begin{array}{cc} 
1/2 & 1/2 & 0\\
1/4 & 1/2 & 1/4\\
0 & 1/2 & 1/2
\end{array}\right)
=(1/4)^{3}\left(\begin{array}{cc} 
20 & 32 & 12\\
16 & 32 & 16\\
12 & 32 & 20
\end{array}\right)\\
\implies The\;probabilities\;that\;any\;offspring;belonging\;to\;first\;generation\;to\;be\;tall\;or\;medium\;or\;short=
\left(\begin{array}{cc}
1/4 &1/2 &1/4
\end{array}\right)\\
\implies The\;probabilities\;that\;any\;offspring;belonging\;to\;second\;generation\;to\;be\;tall,\;medium\;and\;short=(1/4)^{2}
\left(\begin{array}{cc}
4 &8 &4
\end{array}\right)
=\left(\begin{array}{cc}
1/4 &1/2 &1/4
\end{array}\right)\\
\implies The\;probabilities\;that\;any\;offspring;belonging\;to\;third\;generation\;to\;be\;tall,\;medium\;and\;short=(1/4)^{3}
\left(\begin{array}{cc}
16 &32 &16
\end{array}\right)
=\left(\begin{array}{cc}
1/4 &1/2 &1/4
\end{array}\right)\\
$
$
(c)The\;probabilities\;that\;any\;offspring;belonging\;to\;n^{th}\;generation\;to\;be\;tall,\;medium\;and\;short=(1/4)^{n}
\left(\begin{array}{cc}
2^{2n-2} &2^{2n-1} &2^{2n-2}
\end{array}\right)
=\left(\begin{array}{cc}
1/4 &1/2 &1/4
\end{array}\right)\\
$
$$
\blacksquare
$$


$$
\textbf{Question 2}\\
\textbf{Markov Reward Process}
$$
$
(a)The\;states\;of\;markov\;process\;are\;S,1,2,3,4,5,6,7,8,9,W.\\
\;\;\;The\;transition\;matrix\;for\;this\;game\;is=\left(\begin{array}{cc} 
P_{SS} & P_{S1} & P_{S2}&....&P_{SW}\\
P_{1S} & P_{11} & P_{12}&....&P_{1W}\\
. &.&.&....\\
. &.&.&....\\
P_{WS} &P_{W1}&P_{W2}&....&P_{WW}
\end{array}\right)
=
\left(\begin{array}{cc}
0&1/4&1/4&1/4&1/4&0&0&0&0&0&0\\
0&0&1/4&1/4&1/4&1/4&0&0&0&0&0\\
0&0&0&0&0&0&0&1&0&0&0\\
0&0&0&0&1/4&1/4&1/4&1/4&0&0&0\\
0&0&0&0&0&0&0&0&1&0&0\\
0&0&0&0&0&0&1/4&1/4&1/4&1/4&0\\
0&0&0&0&0&0&0&1/4&1/4&1/4&1/4\\
0&0&0&0&0&0&0&1/4&1/4&1/4&1/4\\
0&0&0&0&0&0&0&0&1/2&1/4&1/4\\
0&0&0&1&0&0&0&0&0&0&0\\
0&0&0&0&0&0&0&0&0&0&1\\
\end{array}\right)
$
$
(b)There\;is\;one\;absorbing\;state:StateW.\\
\implies Reward(R(s(t)))=\left(\begin{array}{cc}
1&1&0&1&0&1&1&1&1&0&0
\end{array}\right)
^{T}\\
\implies Discount\;factor(\gamma)=1\\
\implies Average\;no\;of\;steps\;equals\;to\;value\;function\;at\;each\;state.\\
\implies From\;Bell\;man\;equation\;V=(1-\gamma.N)^{-1}.R\;\;where\;N\;is\;fundamental\;matrix.\\
\implies P=\left(\begin{array}{cc}
N & R\\
0 & A
\end{array}\right)\;where\;A\;is\;an\;identity\;matrix\;with\;absorbing\;states.\\
\implies Here\;Fundamental\;matrix(N)=\left(\begin{array}{cc}
0&1/4&1/4&1/4&1/4&0&0&0&0&0\\
0&0&1/4&1/4&1/4&1/4&0&0&0&0\\
0&0&0&0&0&0&0&1&0&0\\
0&0&0&0&1/4&1/4&1/4&1/4&0&0\\
0&0&0&0&0&0&0&0&1&0\\
0&0&0&0&0&0&1/4&1/4&1/4&1/4\\
0&0&0&0&0&0&0&1/4&1/4&1/4\\
0&0&0&0&0&0&0&1/4&1/4&1/4\\
0&0&0&0&0&0&0&0&1/2&1/4\\
0&0&0&1&0&0&0&0&0&0\\
\end{array}\right)\\
\implies We\;have\;to\;remove\;absorbing\;states\;form\;transition\;matrix\;to\;form\;fundamental\;matrix.\\
\implies V=(1-\gamma.N)^{-1}.R\\
\implies V=\left(\begin{array}{cc}
85/12&7&16/3&20/3&16/3&20/3&16/3&16/3&16/3&20/3
\end{array}\right)
^{T}\\
\implies V=\left(\begin{array}{cc}
7.08&7&5.33&6.67&5.33&6.67&5.33&5.33&5.33&6.67
\end{array}\right)
^{T}\\
$

$$
\blacksquare
$$

$$
\textbf{Question 3:}\\
\textbf{Markov Decision Process}
$$
![](https://drive.google.com/uc?id=1Fvs_A4qVhuFPanP1t8hnM463XU3t4zQ3)

$
(b)\implies Deterministic\;policy:\\\pi(s)=\left\{ \begin{array}{ll} Drive(a=1), & if\;S=Top,Rolling,Bottom \\
 \end{array} \right..
 \\\implies Stocastic\;policy\;at\;any\;state:\\\pi(s)=\left\{ \begin{array}{ll} Drive(a=1)\;with\; probability(p)=0.9 \\Not\;Drive(a=0)\;with\;probability(p)=0.1
 \\
 \end{array} \right..
$

$
(c)Transition\;matrix\;for\;Deterministic\;policy:\\
P_{Drive}=\left(\begin{array}{cc}
0.8 & 0.2 &0\\
0.3 & 0.4 &0.3\\
0.7&0.3&0
\end{array}\right)\\
$
![](https://drive.google.com/uc?id=1l95WhodfTNbfPYp3U_ryz-JHRMFY7o3s)
$
Transition\;matrix\;for\;Stocastic\;policy:\\
\implies \pi(a=1/s)=0.9,\pi(a=0/s)=0.1\;\forall\;s\;in\;S\\
P_{Drive}=\left(\begin{array}{cc}
0.8 & 0.2 &0\\
0.3 & 0.4 &0.3\\
0.7&0.3&0
\end{array}\right)\\
$
![](https://drive.google.com/uc?id=1FjdJueS7438aDLDeB5zcXgdJncxEtmpt)
$
P_{NotDrive}=\left(\begin{array}{cc}
0.6 & 0.4 &0\\
0 & 0.1 &0.9\\
0&0&1
\end{array}\right)\\
$
![](https://drive.google.com/uc?id=1VEgSR2zMOIXT_4tbkbi7wvHoz3582R8L)
$
(d)History\;dependent\;policy:\rightarrow History\;dependent\;policy\;depends\;on\;previous\;states\\
Time\;step\;1:a_{1}^{hd}(drive)=drive\\
a_{1}^{hd}(rolling\;down)=drive\\
a_{1}^{hd}(bottom)=drive\\
\rightarrow Time\;step\;2:a_{2}^{hd}(drive,s_{t-1}=top)=Not\;drive\\
a_{2}^{hd}(drive,s_{t-1}=rolling down)=drive\\
a_{2}^{hd}(drive,s_{t-1}=bottom)=drive\\
$

$$
\blacksquare
$$

$$
\textbf{Question 4:}\\
\textbf{Policy Evaluation and Partial Ordering of Policies}
$$
$
Given:Stocastic\;Environment\implies 90 \% of\;the\;times\;and\;fails\;10\;\% \;of\;the\;times.\\
The\;state\;D\;is\;a\;terminal\;state\;with\;reward\;of\;100.\\
$
$
(a)V^{\pi}(s)\;for\;each\;policy:\\
Policy\;1:Policy\;π1\;is\;deterministic\;policy\;that\;chooses\;action\;a1\;at\; all\;states\;s ∈ S.\\
\implies We\;have\;V^{\pi}(s)=\sum_{a}\pi(a/s)\sum_{s^{'}}P^{a}_{ss^{'}}(R^{a}_{ss^{'}}+\gamma.V^{\pi}(s^{'}))\\
\implies V_{\pi}(A)=(0.9)(-10+1.V^{\pi}(B))+(0.1)(-10+1.V^{\pi}(C))\\
\implies V_{\pi}(B)=(0.9)(-10+1.V^{\pi}(D))+(0.1)(-10+1.V^{\pi}(A))\\
\implies V_{\pi}(C)=(0.9)(-10+1.V^{\pi}(A))+(0.1)(-10+1.V^{\pi}(D))\\
\implies V_{\pi}(D)=100\\
\implies V^{\pi}(A)=75.6,V^{\pi}(B)=87.5,V^{\pi}(C)=68.04\\
Policy\;2:Policy\;π2\;is\;deterministic\;policy\;that\;chooses\;action\;a2\;at\; all\;states\;s ∈ S.\\
\implies We\;have\;V^{\pi}(s)=\sum_{a}\pi(a/s)\sum_{s^{'}}P^{a}_{ss^{'}}(R^{a}_{ss^{'}}+\gamma.V^{\pi}(s^{'}))\\
\implies V_{\pi}(A)=(0.9)(-10+1.V^{\pi}(C))+(0.1)(-10+1.V^{\pi}(B))\\
\implies V_{\pi}(B)=(0.9)(-10+1.V^{\pi}(A))+(0.1)(-10+1.V^{\pi}(D))\\
\implies V_{\pi}(C)=(0.9)(-10+1.V^{\pi}(D))+(0.1)(-10+1.V^{\pi}(A))\\
\implies V_{\pi}(D)=100\\
\implies V^{\pi}(A)=75.6,V^{\pi}(B)=68.04,V^{\pi}(C)=87.5\\
Policy\;3:Policy\;π3\;is\;a\;stochastic\;policy\\
\implies We\;have\;V^{\pi}(s)=\sum_{a}\pi(a/s)\sum_{s^{'}}P^{a}_{ss^{'}}(R^{a}_{ss^{'}}+\gamma.V^{\pi}(s^{'}))\\
\implies V_{\pi}(A)=(0.6)(0.1)(-10+1.V^{\pi}(B))+(0.4)(0.1)(-10+1.V^{\pi}(C))+
(0.4)(0.9)(-10+1.V^{\pi}(B))+(0.9)(0.6)(-10+1.V^{\pi}(C))=(0.58)(-10+1.V^{\pi}(C))+(0.42)(-10+1.V^{\pi}(B)).\\
\implies V_{\pi}(B)=(0.9)(-10+1.V^{\pi}(A))+(0.1)(-10+1.V^{\pi}(D)).\\
\implies V_{\pi}(C)=(0.9)(-10+1.V^{\pi}(D))+(0.1)(-10+1.V^{\pi}(A)).\\
\implies V_{\pi}(D)=100\\
\implies V^{\pi}(A)=77.7778,V^{\pi}(B)=87.77778,V^{\pi}(C)=87.77778\\
$
$
(b)Best\;policy\;among\;the\;policies:We\;can\;clearly\;observe\;that\;\pi_{3}\;is\;best\;policy\;since\;V^{\pi_{3}}(A)>V^{\pi_{1}}(A),V^{\pi_{3}}(B)>V^{\pi_{1}}(B),V^{\pi_{3}}(C)>V^{\pi_{1}}(C)\;and\;V^{\pi_{3}}(A)>V^{\pi_{2}}(A),V^{\pi_{3}}(B)>V^{\pi_{2}}(B),V^{\pi_{3}}(C)>V^{\pi_{2}}(C).
$

$
(c)Two\;policies\;are\;comparable\;\implies V^{\pi_{a}}(s)>V^{\pi_{b}}(s)\;\forall
s ∈ S\\
\implies V^{\pi_{1}},V^{\pi_{2}}\;are\;not\;comparable\;since\;V^{\pi_{1}}(B)>V^{\pi_{2}}(B)\;and\;V^{\pi_{1}}(C)<V^{\pi_{2}}(C)
$
$$
\blacksquare
$$

$$
\textbf{Question 5:}\\
\textbf{ Optimal Policies}
$$
$
Given:A\;policy\;π^{*}\;of\;an\;MDP\;is\;said\;to\;be\;optimal\;if\;π^{*}\;∈\;Π\;\\ where\;Π = arg max_{π}(V_{π}(s)) = arg max_{\pi}(E_{π} (rt+1 + γrt+1 + · · · |st = s))\\
\implies We\;can\;find\;optimal\;policy\;through\;policy\;iteration.\\
\implies \textbf{Policy iteration algorithm:}\\
Start\;with\;any\;initial\;policy\;\pi_{1}.\\
\;\;\textbf{for}\;i=1,2,......,N\;\textbf{do}:\\
\;\;\;\;\;Evaluate\;V^{\pi_{i}}(s)\;\forall\;s\in S.That\;is\\
\;\;\;\;\; for\;k = 1,2,··· ,K\;\textbf{do}:\\
\;\;\;\;\;\;\;\;For\;all\;s ∈S\;calculate: \\
\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;V^{\pi_{i}}_{k+1}(s)\leftarrow\sum_{a}\pi(a/s)\sum_{s^{'}}P^{a}_{ss^{'}}(R^{a}_{ss^{'}}+\gamma.V^{\pi_{i}}_{k}(s^{'}))\\
\\
\;\;\;\;\;\;\textbf{end for}\\
\;\;\;\;\;\;Perform\;policy\;Improvement\\
\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\pi_{i+1} = greedy(V_{\pi_{i}} )\\
\textbf{end for}\\
\implies\;Proof\;that\;it\;attains\;optimal\;policy\\
\rightarrow Consider\;a\;Deterministic\;policy\;a=\pi(s)
\rightarrow \pi^{'}(s)=argmax_{a}(Q^{\pi}(s,a))\\
\rightarrow This\;improves\;the\;value\;from\;any\;state\;s\;over\;one\;step.\\
Q^{\pi}(s,\pi^{'}(s))=max_{a}(Q^{\pi}(s,a))\geq Q^{\pi}(s,\pi(s))=V^{\pi}(s).\\
\implies V^{pi^{'}(s)}\geq V_{\pi}(s)
\implies It\;therefore\;improves\;the\;value\;function.\\
\rightarrow If\;improvement\;stops:\\
Q^{\pi}(s,\pi^{'}(s))=max_{a}(Q^{\pi}(s,a))= Q^{\pi}(s,\pi(s))=V^{\pi}(s).\\
\implies Bellman\;optimalityequation\;is\;satisfied.\\
V^{\pi}(s)=max_{a}(Q^{\pi}(s,a))\\
\implies The\;policy\;\pi\;for\;which\;the\;improvement\;stops\;is\;optimal\;\\V^{\pi}(s)=V_{*}(s)\;\forall \;s\in S.
$
$$
\blacksquare
$$

$$
\textbf{Question 6:}\\
\textbf{Value Iteration}
$$
$
(a)\textbf{Optimal policy:}\\The\;optimal\;policy\;is\;to\;move\;right,i.e\;\pi(s)={R}\;\forall s\in {s_{1},s_{2},s_{3},s_{4},s_{5}}.\\
\textbf{Optimal value function:}\\
\implies We\;have\;V^{\pi}(s)=\sum_{a}\pi(a/s)\sum_{s^{'}}P^{a}_{ss^{'}}(R^{a}_{ss^{'}}+\gamma.V^{\pi}(s^{'}))\\
\implies V^{\pi}(s_{1})=0+(1).(V^{\pi}(s_{2}))\\
\implies V^{\pi}(s_{2})=0+(1).(V^{\pi}(s_{3}))\\
\implies V^{\pi}(s_{3})=0+(1).(V^{\pi}(s_{4}))\\
\implies V^{\pi}(s_{4})=0+(1).(V^{\pi}(s_{5}))\\
\implies V^{\pi}(s_{5})=0+(1).(V^{\pi}(s_{6}))\\
\implies terminal\;state(V^{\pi}(s_{6}))=10\\
\implies V^{\pi}(s_{1})=V^{\pi}(s_{2})=V^{\pi}(s_{3})=V^{\pi}(s_{4})=V^{\pi}(s_{5})=10
$
$
(b)Given\;\gamma={0.9, 0.5, 0.1}.\\
\textbf{Value function for different discount factors:}\\
\implies V^{\pi}(s_{1})=0+(\gamma).(V^{\pi}(s_{2}))\\
\implies V^{\pi}(s_{2})=0+(\gamma).(V^{\pi}(s_{3}))\\
\implies V^{\pi}(s_{3})=0+(\gamma).(V^{\pi}(s_{4}))\\
\implies V^{\pi}(s_{4})=0+(\gamma).(V^{\pi}(s_{5}))\\
\implies V^{\pi}(s_{5})=0+(\gamma).(V^{\pi}(s_{6}))\\
\implies terminal\;state(V^{\pi}(s_{6}))=10\\
\implies V^{\pi}(s_{1})=10\gamma ^{5},V^{\pi}(s_{2})=10\gamma ^{4},V^{\pi}(s_{3})=10\gamma ^{3},V^{\pi}(s_{4})=10\gamma ^{2},V^{\pi}(s_{5})=10\gamma ^{1}.\\ 
\implies We\;can\;see\;with\;new\;gamma\;the\;policy\;doesn't\;change.\;\\
$
$
(c)\textbf{Adding a constant c for the rewards of all the states:}\\
\implies The\;optimal\;policy\;is\;to\;move\;right.
\implies V^{\pi}(s_{1})=c+(\gamma).(V^{\pi}(s_{2}))\\
\implies V^{\pi}(s_{2})=c+(\gamma).(V^{\pi}(s_{3}))\\
\implies V^{\pi}(s_{3})=c+(\gamma).(V^{\pi}(s_{4}))\\
\implies V^{\pi}(s_{4})=c+(\gamma).(V^{\pi}(s_{5}))\\
\implies V^{\pi}(s_{5})=c+(\gamma).(V^{\pi}(s_{6}))\\
\implies terminal\;state(V^{\pi}(s_{6}))=10+c\\
\implies V^{\pi}(s_{1})=c(1+\gamma+...+\gamma^{4})+10.\gamma^{5}\\
\implies V^{\pi}(s_{2})=c(1+\gamma+...+\gamma^{3})+10.\gamma^{4}\\
\implies V^{\pi}(s_{3})=c(1+\gamma+\gamma^{2})+10.\gamma^{3}\\
\implies V^{\pi}(s_{4})=c(1+\gamma)+10.\gamma^{2}\\
\implies V^{\pi}(s_{5})=c+10.\gamma\\
\implies V^{\pi}(s_{6})=10+c\\
\implies The\;optimal\;policy\;doesn't\;change\;we\;see\;it\;through\;value\;iteration.
$

$
(d)Relation\;between \;V^{\pi}\;and\;\tilde V^{\pi}:\\
\implies we\;have\;V^{\pi}(s)=E_{\pi}(G_{t}/S_{t}=s)\\
\implies V^{\pi}(s)=E_{\pi}(\sum_{k=0}^{\infty}\gamma^{k}(R_{t+k+1}/s_{t}=s))\\
\implies we\;have\;\tilde V^{\pi}(s)=E_{\pi}(\tilde G_{t}/S_{t}=s)\\
\implies Given\;that\;\tilde G_{t}=G_{t}+c\\
\implies \tilde V^{\pi}(s)=E_{\pi}(\sum_{k=0}^{\infty}\gamma^{k}(R_{t+k+1}+c/s_{t}=s))\\
\implies \tilde V^{\pi}(s)=E_{\pi}(\sum_{k=0}^{\infty}\gamma^{k}(R_{t+k+1}/s_{t}=s))+c.E_{\pi}(\sum_{k=0}^{\infty}\gamma^{k}/s_{k}=s)\\
\implies \tilde V^{\pi}(s)=V^{\pi}(s)+\frac{c}{1-\gamma}
\implies We\;can\;see\;the\;relative\;values\;of\;rewards\;doesn't\;changed\;by\;adding\;a\;constant.\\
\implies The\;policy\;doesn't\;change\;it\;remains\;going\;to\;right
$
$$
\blacksquare
$$

$$
\textbf{Question 7:}\\
\textbf{ Effect of Noise and Discounting}
$$

In [0]:
import numpy as np
import matplotlib.pyplot as plt
obstacles=[(1,1),(2,1),(2,3)]

$$
Function\;for\;improving\;value\;functions\;greedily
$$

In [0]:
def greedy(i,j,noise,gamma,Vinitial):
  up,down,left,right=0,0,0,0
  if i>0 and ((i-1,j) not in obstacles):
    up=gamma*Vinitial[i-1][j]
  elif i==0 or ((i-1,j) in obstacles):
    up=gamma*Vinitial[i][j]
  if i<4 and ((i+1,j) not in obstacles):
    down=gamma*Vinitial[i+1][j]
  elif i==4 or ((i+1,j) in obstacles):
    down=gamma*Vinitial[i][j]
  if j>0 and ((i,j-1) not in obstacles):
    left=gamma*Vinitial[i][j-1]
  elif j==0 or ((i,j-1) in obstacles):
    left=gamma*Vinitial[i][j]
  if j<4 and ((i,j+1) not in obstacles):
    right=gamma*Vinitial[i][j+1]
  elif j==4 or ((i,j+1) in obstacles):
    right=gamma*Vinitial[i][j]
  total_reward=up+down+right+left
  up_reward=(1-noise)*up+(noise/3)*(total_reward-up)
  down_reward=(1-noise)*down+(noise/3)*(total_reward-down)
  left_reward=(1-noise)*left+(noise/3)*(total_reward-left)
  right_reward=(1-noise)*right+(noise/3)*(total_reward-right)
  return max(up_reward,down_reward,left_reward,right_reward)

$$
Policy\;iteration
$$

In [0]:
def Policy_iteration(iterations,noise,gamma,Vinitial):
  for k in range(iterations):
    for i in range(np.shape(Vinitial)[0]):
      for j in range(np.shape(Vinitial)[1]):
        if (i,j) in obstacles or(i==2 and j==2)or(i==2 and j==np.shape(Vinitial)[1]-1)or(i==np.shape(Vinitial)[0]-1):
          continue
        else :
          Vinitial[i][j]=greedy(i,j,noise,gamma,Vinitial)
  return Vinitial

$$
Policy\;iteration\;with\;\gamma=0.1\;and\;noise=0.5
$$

In [0]:
V1=[[0,0,0,0,0]
    ,[0,0,0,0,0]
    ,[0,0,1,0,10]
    ,[0,0,0,0,0]
    ,[-10,-10,-10,-10,-10]]

V1=Policy_iteration(iterations=4000
                   ,noise=0.5
                  ,gamma=0.1
                  ,Vinitial=V1)
print("Value Function matrix after Policy Iteration")
print(np.array(V1))

Value Function matrix after Policy Iteration
[[ 6.20061487e-06  1.36896486e-04  2.64459852e-03  1.85474875e-03
   2.63790105e-02]
 [-5.10537939e-05  0.00000000e+00  5.13465557e-02  2.68021892e-02
   5.09375953e-01]
 [-2.97972189e-03  0.00000000e+00  1.00000000e+00  0.00000000e+00
   1.00000000e+01]
 [-1.72670708e-01 -1.78632633e-01 -1.22218206e-01 -1.54459711e-01
   3.36365090e-01]
 [-1.00000000e+01 -1.00000000e+01 -1.00000000e+01 -1.00000000e+01
  -1.00000000e+01]]


$$
\textbf{Observations}
$$
$
\rightarrow Prefer\;the\;close\;exit\;(state\;with\;reward\;+1)\;by\;avoiding\;the\;cliff\; (solid\;path\;to\;+1)
$

$$
Value\;iteration\;with\;\gamma=0.1\;and\;noise=0
$$

In [0]:
V2=[[0,0,0,0,0]
    ,[0,0,0,0,0]
    ,[0,0,1,0,10]
    ,[0,0,0,0,0]
    ,[-10,-10,-10,-10,-10]]

V2=Policy_iteration(iterations=4000
                   ,noise=0
                  ,gamma=0.1,
                  Vinitial=V2)
print("Value Function matrix after Policy Iteration")
print(np.array(V2))

Value Function matrix after Policy Iteration
[[ 1.e-04  1.e-03  1.e-02  1.e-02  1.e-01]
 [ 1.e-05  0.e+00  1.e-01  1.e-01  1.e+00]
 [ 1.e-04  0.e+00  1.e+00  0.e+00  1.e+01]
 [ 1.e-03  1.e-02  1.e-01  1.e-01  1.e+00]
 [-1.e+01 -1.e+01 -1.e+01 -1.e+01 -1.e+01]]


$$
\textbf{Observations}
$$
$
\rightarrow \;Prefer\;the\;close\;exit\;(state\;with\;reward\;+1)\;but\;risk\;the\;cliff (dashed\;path\;to\;+1)
$

$$
Value\;iteration\;with\;\gamma=0.9\;and\;noise=0
$$

In [0]:
V3=[[0,0,0,0,0]
    ,[0,0,0,0,0]
    ,[0,0,1,0,10]
    ,[0,0,0,0,0]
    ,[-10,-10,-10,-10,-10]]

V3=Value_iteration(iterations=4000
                   ,noise=0
                  ,gamma=0.9,
                  Vinitial=V3)
print("Value Function matrix after Policy Iteration")
print(np.array(V3))

Value Function matrix after Policy Iteration
[[  5.31441    5.9049     6.561      7.29       8.1     ]
 [  4.782969   0.         7.29       8.1        9.      ]
 [  5.31441    0.         1.         0.        10.      ]
 [  5.9049     6.561      7.29       8.1        9.      ]
 [-10.       -10.       -10.       -10.       -10.      ]]


$$
\textbf{Observations}
$$
$
\rightarrow Prefer\;the\;distant\;exit\;(state\;with\;reward\;+10)\;but\;risk\;the\;cliff\;(dashed\; path\; to\;+10).
$

$$
Value\;iteration\;with\;gamma=0.9\;and\;noise=0.5
$$

In [0]:
V4=[[0,0,0,0,0]
    ,[0,0,0,0,0]
    ,[0,0,1,0,10]
    ,[0,0,0,0,0]
    ,[-10,-10,-10,-10,-10]]

V4=Value_iteration(iterations=4000
                   ,noise=0.5
                  ,gamma=0.9,
                  Vinitial=V4)
print("Value Function matrix after Policy Iteration")
print(np.array(V4))

Value Function matrix after Policy Iteration
[[  2.01684288   2.67225336   3.4845576    4.50288017   5.59761815]
 [  1.39517334   0.           3.56493254   5.23890892   7.20644595]
 [  0.46028028   0.           1.           0.          10.        ]
 [ -2.03754538  -2.9269313   -1.51613289  -0.18062129   3.49753742]
 [-10.         -10.         -10.         -10.         -10.        ]]


$$
Observations
$$
$
\rightarrow Prefer\;the\;distant\;exit\;(state\;with\;reward\;+10)\;by\;avoiding\;the\;cliff\;(solid\; path\;to\;+10).
$

$$
\textbf{Question 8:}\\
\textbf{Convergence Rate of Value Iteration}
$$
$
We\;have\;V_{k+1}(s)\leftarrow max[\sum_{s^{'}\in S}P^{a}_{ss^{'}}(R^{a}_{ss^{'}}+\gamma V_{k}(s^{'}))]\\
\rightarrow Since\;environment\;is\;deterministic:\\
V_{k+1}(s)\leftarrow max[\sum_{s^{'}\in S}(R^{a}_{ss^{'}}+\gamma\sum_{s^{'}\in S}P^{a}_{ss^{'}}.V_{k}(s^{'}))]\\
\implies we\;have\;Bellman\;operator\rightarrow L(v)=max_{a\in A}(R^{a}+\gamma.P^{a}V)\\
\implies L(v_{k})=V_{k+1}\\
\implies for\;convergence\;Lt_{k\rightarrow \infty}L(V_{k})=V^{*}.\\
\implies Inorder\;to\;prove\;value\;iteration\;converges\;we\;have\;to\;show\;that\;||V_{k+1}-V*||_{\infty}\;converges.\\
\rightarrow Consider\;||V_{k+1}-V*||_{\infty}=||L(V_{k})-L(V*)||_{\infty}\leq\gamma||V_{k}-V*||_{\infty}\\
\rightarrow we\;have\;\gamma||V_{k}-V*||_{\infty}=\gamma||L(V_{k-1})-L(V*)||_{\infty}\\
\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\leq \gamma^{2}||V_{k-1}-V*||_{\infty}\\
\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\leq \gamma^{3}||V_{k-2}-V*||_{\infty}\\
\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;..\\
\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;..\\
\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;..\\
\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\leq \gamma^{k}||V_{1}-V*||_{\infty}\\
\implies The\;term\;\gamma^{k}||V_{1}-V*||_{\infty}converges\;goemetrically\;to\;zero.i.e\;||V_{k+1}-V*||_{\infty}\rightarrow 0.\\
\therefore Value\;iteration\;converges\;geometrically.
$